version: '3'

services:
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 5000:3306
    environment:
      # the default user is root
      MYSQL_ROOT_PASSWORD: example
