version: '3'

networks:
  internal-tier:

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   command: npm start
  #   restart: always
  #   ports:
  #     - ${API_PORT}:3000
  #   volumes:
  #     - ./src:/app/src
  #   networks:
  #     - internal-tier
  #   depends_on:
  #     - mysqldb
  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - internal-tier
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
